apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_RESOURCE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${K8S_RESOURCE_NAME}
  template:
    metadata:
      labels:
        app: ${K8S_RESOURCE_NAME}
    spec:
      containers:
        - name: ${K8S_RESOURCE_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          envFrom:
            - secretRef:
                name: meyasubako-env

---
apiVersion: v1
kind: Service
metadata:
  name: ${K8S_RESOURCE_NAME}
spec:
  ports:
    - port: 3000
      nodePort: ${K8S_NODEPORT}
  selector:
    app: ${K8S_RESOURCE_NAME}
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${K8S_RESOURCE_NAME}
spec:
  rules:
    - host: ${K8S_RESOURCE_NAME}.jtektrnd.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${K8S_RESOURCE_NAME}
                port:
                  number: 3000
